#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900
#define VIEWPORT_WIDTH 16
#define VIEWPORT_HEIGHT 9
#define VIEWPORT_DISTANCE 10
#define MAX_RECURSION_DEPTH 2

#endif // CONSTANTS_H
